<a href="https://colab.research.google.com/github/solobala/FEML23/blob/master/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%D1%81_%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Импорты

In [1]:
!pip install pymorphy2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 42.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13721 sha256=9656747a22f51fa44e15511e754c3fb0881801188ed68e8e0f7aae961b27c722
  Stored in directory: /root/.cache/pip/wheels/70/4a/46/1309fc853b8d395e60bafaf1b6df7845bdd82c95fd59dd8d2b
Successfully built docopt


## CountVectorizer

In [2]:
from sklearn.feature_extraction.text import CountVectorizer # персчитает слова, сделает словарь и вернет onehot вектора

corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',]


In [3]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus) # одновременно и обучение, и трансформация
print(vectorizer.get_feature_names_out())
print(X.toarray())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


n-граммы

In [4]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(1, 3)) # хотим учесть группы слов, -устойчивые словосочетания( здесь от 1 до 3 слов)
X2 = vectorizer2.fit_transform(corpus)
print(vectorizer2.get_feature_names_out())
print(X2.toarray())

['and' 'and this' 'and this is' 'document' 'document is' 'document is the'
 'first' 'first document' 'is' 'is the' 'is the first' 'is the second'
 'is the third' 'is this' 'is this the' 'one' 'second' 'second document'
 'the' 'the first' 'the first document' 'the second' 'the second document'
 'the third' 'the third one' 'third' 'third one' 'this' 'this document'
 'this document is' 'this is' 'this is the' 'this the' 'this the first']
[[0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0]
 [0 0 0 2 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0]
 [1 1 1 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0]
 [0 0 0 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1]]


## TFIDF

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer # один способ , есть еще TFIDFTransformer

In [6]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(X) # выводим в разреженной форме( sparse-матрица). Только то, где есть числа кроме 0

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
  (0, 1)	0.46979138557992045
  (0, 2)	0.5802858236844359
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 8)	0.38408524091481483
  (1, 5)	0.5386476208856763
  (1, 1)	0.6876235979836938
  (1, 6)	0.281088674033753
  (1, 3)	0.281088674033753
  (1, 8)	0.281088674033753
  (2, 4)	0.511848512707169
  (2, 7)	0.511848512707169
  (2, 0)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 3)	0.267103787642168
  (2, 8)	0.267103787642168
  (3, 1)	0.46979138557992045
  (3, 2)	0.5802858236844359
  (3, 6)	0.38408524091481483
  (3, 3)	0.38408524091481483
  (3, 8)	0.38408524091481483


## Токенизация и разбор предложения

In [7]:
import nltk
nltk.download('punkt') # 
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
from nltk.tokenize import sent_tokenize # разбивает предложение на слова
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [9]:
text = "Backgammon is one of the oldest known board games. Its history can be traced back nearly 5,000 years to archeological discoveries in the Middle East. It is a two player game where each player has fifteen checkers which move between twenty-four points according to the roll of two dice."
sentences = sent_tokenize(text) # текст делим на предложения, а предложения на слова
for sentence in sentences:
    tokens = word_tokenize(sentence)
    print(tokens)

['Backgammon', 'is', 'one', 'of', 'the', 'oldest', 'known', 'board', 'games', '.']
['Its', 'history', 'can', 'be', 'traced', 'back', 'nearly', '5,000', 'years', 'to', 'archeological', 'discoveries', 'in', 'the', 'Middle', 'East', '.']
['It', 'is', 'a', 'two', 'player', 'game', 'where', 'each', 'player', 'has', 'fifteen', 'checkers', 'which', 'move', 'between', 'twenty-four', 'points', 'according', 'to', 'the', 'roll', 'of', 'two', 'dice', '.']


In [10]:
import pymorphy2
import re
morph = pymorphy2.MorphAnalyzer()
stop_words = stopwords.words('russian')

text = "Обработка текстов на естественном языке — общее направление искусственного интеллекта и математической лингвистики. Оно изучает проблемы компьютерного анализа и синтеза текстов на естественных языках. Применительно к искусственному интеллекту анализ означает понимание языка, а синтез — генерацию грамотного текста."
sentences = nltk.sent_tokenize(text, language="russian")
for sentence in sentences:
    print('___________________')
    print(sentence)
    sentence_ = re.sub(r"[^А-Яа-яёЁ ]","", sentence) # удалим все кроме букв
    print(sentence_)
    tokens = nltk.word_tokenize(sentence_) # поделим на слова
    print(tokens)
    tokens = [i for i in tokens if (i not in stop_words)]
    print(tokens)
    tokens = list(map(lambda x: morph.parse(x)[0].normal_form, tokens)) # возьмем самую частую нормальную форму
    print(tokens)

___________________
Обработка текстов на естественном языке — общее направление искусственного интеллекта и математической лингвистики.
Обработка текстов на естественном языке  общее направление искусственного интеллекта и математической лингвистики
['Обработка', 'текстов', 'на', 'естественном', 'языке', 'общее', 'направление', 'искусственного', 'интеллекта', 'и', 'математической', 'лингвистики']
['Обработка', 'текстов', 'естественном', 'языке', 'общее', 'направление', 'искусственного', 'интеллекта', 'математической', 'лингвистики']
['обработка', 'текст', 'естественный', 'язык', 'общий', 'направление', 'искусственный', 'интеллект', 'математический', 'лингвистика']
___________________
Оно изучает проблемы компьютерного анализа и синтеза текстов на естественных языках.
Оно изучает проблемы компьютерного анализа и синтеза текстов на естественных языках
['Оно', 'изучает', 'проблемы', 'компьютерного', 'анализа', 'и', 'синтеза', 'текстов', 'на', 'естественных', 'языках']
['Оно', 'изучает', '

In [11]:
morph.parse('банка')

[Parse(word='банка', tag=OpencorporaTag('NOUN,inan,masc sing,gent'), normal_form='банк', score=0.954545, methods_stack=((DictionaryAnalyzer(), 'банка', 19, 1),)),
 Parse(word='банка', tag=OpencorporaTag('NOUN,inan,femn sing,nomn'), normal_form='банка', score=0.045454, methods_stack=((DictionaryAnalyzer(), 'банка', 8, 0),))]

##word2vec

In [ ]:
!wget http://vectors.nlpl.eu/repository/20/65.zip # Это для русского языка

--2023-04-25 18:36:40--  http://vectors.nlpl.eu/repository/20/65.zip
Resolving vectors.nlpl.eu (vectors.nlpl.eu)... 129.240.189.181
Connecting to vectors.nlpl.eu (vectors.nlpl.eu)|129.240.189.181|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2540031150 (2.4G) [application/zip]
Saving to: ‘65.zip’

65.zip              100%[===================>]   2.37G  26.6MB/s    in 93s     

2023-04-25 18:38:13 (26.2 MB/s) - ‘65.zip’ saved [2540031150/2540031150]



In [ ]:
! unzip 65.zip

Archive:  65.zip
  inflating: LIST                    
  inflating: meta.json               
  inflating: model.bin               
  inflating: model.txt               
  inflating: README                  


In [ ]:
from gensim.models import KeyedVectors

filename = 'model.bin'
model = KeyedVectors.load_word2vec_format(filename, binary=True)
result = model.most_similar(positive=['женщина', 'король'], negative=['мужчина'], topn=10)
print(result)

[('кастильская', 0.7397260069847107), ('ченла', 0.7331686019897461), ('королева-', 0.7280980944633484), ('принцесса', 0.7141850590705872), ('джаядеви', 0.7126126885414124), ('фландрская', 0.7091805934906006), ('анжуйская', 0.7086013555526733), ('наваррская', 0.7060782313346863), ('арагонская', 0.7054516077041626), ('королева-мать', 0.703084409236908)]


In [12]:
!wget http://vectors.nlpl.eu/repository/20/222.zip # Это для английского

--2023-04-26 07:18:32--  http://vectors.nlpl.eu/repository/20/222.zip
Resolving vectors.nlpl.eu (vectors.nlpl.eu)... 129.240.189.181
Connecting to vectors.nlpl.eu (vectors.nlpl.eu)|129.240.189.181|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 508672665 (485M) [application/zip]
Saving to: ‘222.zip’

222.zip             100%[===================>] 485.11M   935KB/s    in 4m 36s  

2023-04-26 07:23:09 (1.76 MB/s) - ‘222.zip’ saved [508672665/508672665]



In [13]:
! unzip 222.zip

Archive:  222.zip
  inflating: meta.json               
  inflating: model.bin               
  inflating: model.txt               
  inflating: README                  


In [14]:
from gensim.models import KeyedVectors

filename = 'model.bin'
model = KeyedVectors.load_word2vec_format(filename, binary=True)
result = model.most_similar(positive=['woman', 'king'], negative=['man'], topn=10)
print(result)

[('queen', 0.7247692346572876), ('monarch', 0.7230237126350403), ('princess', 0.6840912103652954), ('kings', 0.6651214361190796), ('ruler', 0.6376540660858154), ('prince', 0.6370851397514343), ('kingdom', 0.609379231929779), ('regnant', 0.6011638045310974), ('monarchs', 0.5959004759788513), ('consort', 0.5871730446815491)]


## Распознание спама


In [ ]:
#Загружаем данные и разархивируем

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip # датасети смсок

--2023-04-25 18:13:16--  https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 203415 (199K) [application/x-httpd-php]
Saving to: ‘smsspamcollection.zip’

smsspamcollection.z 100%[===================>] 198.65K   723KB/s    in 0.3s    

2023-04-25 18:13:17 (723 KB/s) - ‘smsspamcollection.zip’ saved [203415/203415]



In [ ]:
!unzip smsspamcollection.zip

Archive:  smsspamcollection.zip
  inflating: SMSSpamCollection       
  inflating: readme                  


In [ ]:
import torch
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_table('SMSSpamCollection',sep='\t',header=None, names=['label','sms_message'])

In [ ]:
#Данные 

In [ ]:
df.head()

label                                        sms_message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

### Логистическая регрессия + TFIDF

In [ ]:
data_corp = [ " ".join(df[df['label'] == l]['sms_message'].tolist()) for l in list(df.label.unique()) ] #  складываем

In [ ]:
data_corp

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat... Ok lar... Joking wif u oni... U dun say so early hor... U c already then say... Nah I don\'t think he goes to usf, he lives around here though Even my brother is not like to speak with me. They treat me like aids patent. As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune I\'m gonna be home soon and i don\'t want to talk about this stuff anymore tonight, k? I\'ve cried enough today. I\'ve been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times. I HAVE A DATE ON SUNDAY WITH WILL!! Oh k...i\'m watching here:) Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet. Fine if that\x92s the way u feel. That\x92s t

In [ ]:
vectorizer = TfidfVectorizer()
vectorizer.fit(data_corp)

TfidfVectorizer()

In [ ]:
df['sms_message'] #никакую преолдобработку не делали

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: sms_message, Length: 5572, dtype: object

In [ ]:
vectorizer.transform(['The guy did some bitching but I acted like'])

<1x8713 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
res_tfidf = vectorizer.transform(df['sms_message'].tolist())


In [ ]:
res_tfidf[0].todense() # За каждым смс сообшением- стоит tfidf вектор

matrix([[0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, classification_report
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder().fit(df['label'])

In [ ]:
df['cat_label'] = le.transform(df['label'])

In [ ]:
df['cat_label'].value_counts()

0    4825
1     747
Name: cat_label, dtype: int64

In [ ]:
X_tr, X_ts, y_tr, y_ts=train_test_split(res_tfidf, df['cat_label'], test_size=0.2)

In [ ]:
lr = LogisticRegression().fit(X_tr, y_tr)

In [ ]:
y_pred = lr.predict(X_ts)
f1_score(y_ts, y_pred)

0.8837209302325583

In [ ]:
print(classification_report(y_ts, y_pred)) # f1score не чувствительна к дисбалансу

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       973
           1       0.98      0.80      0.88       142

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115



### Наивный Байесовский классификатор

In [ ]:
#заменяем целевую переменную

In [ ]:
df['label'] = df.label.map({'ham':0,'spam':1})

In [ ]:
#Делим на трейновую и тестовую выборку
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['sms_message'], df['label'], random_state=1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [ ]:
#Считаем количество слов в предложениях
#получим матрицу размером (количество предложений Х размер словаря)

count_vector = CountVectorizer()
train_tensor = count_vector.fit_transform(X_train).toarray().astype('float')
test_tensor = count_vector.transform(X_test).toarray().astype('float')


In [ ]:
# размер трейновой выборки
train_tensor.shape

(4179, 7456)

In [ ]:
# всего слов в предложениях
train_tensor.sum()

59839.0

In [ ]:
# тензор с предложениями класса spam
spam_train_tensor = train_tensor[(y_train == 1).values]

# тензор с предложениями класса not_spam
not_spam_train_tensor = train_tensor[(y_train == 0).values]

In [ ]:

#Вероятность слова при условии что предложение спам
p_w_spam = (spam_train_tensor.sum(axis=0)) / (spam_train_tensor.sum())

#Вероятность слова при условии что предложение не спам
p_w_not_spam = (not_spam_train_tensor.sum(axis=0)) / (not_spam_train_tensor.sum())


In [ ]:
# вероятность, что любое сообщение спам
p_spam = (y_train == 1).values.sum() / len(y_train)

# вероятность, что любое сообщение не спам
p_not_spam = (y_train == 0).values.sum() / len(y_train)

In [ ]:
#проверим на одном семпле
test_sample = test_tensor[0]

In [ ]:
# посчитает значение за спам 
np.log(p_spam) + (np.log((test_sample*p_w_spam)+0.00000001)).sum()

-137320.33881535986

In [ ]:
#посчитаем значение против спама
np.log(p_not_spam) + (np.log((test_sample*p_w_not_spam)+0.00000001)).sum()

-137297.9759619618

In [ ]:
# видно что значение против спама больше, чем значение за спам 
# соответственно значение не спам

In [ ]:
#посчитаем для всей тестовой выборки

#размер тестовой выборки
test_tensor.shape

(1393, 7456)

In [ ]:
#посчитаем предсказания как сравнение величинв за спам и против спама
y_pred = (np.log(p_spam) + (np.log((test_tensor*p_w_spam)+0.00000001)).sum(axis=1)) >= \
 np.log(p_not_spam) + (np.log((test_tensor*p_w_not_spam)+0.00000001)).sum(axis=1)

In [ ]:
# предсказанные значения
y_pred.astype(int)

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
#истиные значение
y_test.to_numpy()

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
#сравним реальные метки с предсказанными
test = (y_pred.astype(int) == y_test.to_numpy())

In [ ]:
#посчитаем точность модели как отношение количество совпадений к размеру выборки  
test.sum().item()/test.shape[0]

0.9892318736539842

In [ ]:
print(classification_report(y_test.to_numpy(), y_pred.astype(int)))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.97      0.95      0.96       185

    accuracy                           0.99      1393
   macro avg       0.98      0.97      0.98      1393
weighted avg       0.99      0.99      0.99      1393

